services:
  satisfactory:
    container_name: ${SERVICE}
    image: wolveix/satisfactory-server:latest
    restart: unless-stopped
    ports:
      - 7777:7777/udp
      - 15000:15000/udp
      - 15777:15777/udp
    volumes:
      - data:/config
    networks:
      - traefik
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 12G

volumes:
  data:
    driver: local

networks:
  traefik:
    external: true
