services:
  traefik:
    container_name: traefik
    image: traefik:v2.6
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    networks:
      - traefik
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.${SERVICE}.rule=Host(`${TRAEFIK_DOMAIN}`)
    #   - traefik.http.routers.${SERVICE}.entrypoints=https
    #   - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
    #   - traefik.http.routers.${SERVICE}.service=api@internal
    #   - traefik.http.routers.${SERVICE}.middlewares=strip
    #   - traefik.http.middlewares.strip.stripprefix.prefixes=/traefik
    #   - traefik.http.routers.api.middlewares=authelia@docker
    #   - traefik.http.routers.${SERVICE}.middlewares=authelia@docker
    #   - traefik.http.services.${SERVICE}.loadbalancer.server.port=8080
    environment:
      - TZ=Europe/Berlin
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_TOKEN}
    command:
      - --log.level=${LOG_LEVEL}
      - --providers.docker=true
      - --api.dashboard=false
      - --api.insecure=false
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=$ACME_EMAIL
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # http
      - --entrypoints.http.address=:${HTTP_PORT}
      - --entrypoints.http.http.redirections.entrypoint.to=https
      # https
      - --entrypoints.https.address=:${HTTPS_PORT}
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.https.http.tls=true
      - --entrypoints.https.http.tls.certResolver=letsencrypt
      - --entrypoints.https.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.https.http.tls.domains[0].sans=*.${DOMAIN}

  traefik-certs-dumper:
    image: ldez/traefik-certs-dumper:v2.8.1
    entrypoint: sh -c '
      apk add jq
      ; while ! [ -e /data/acme.json ]
      || ! [ `jq ".[] | .Certificates | length" /data/acme.json` != 0 ]; do
      sleep 1
      ; done
      && traefik-certs-dumper file --version v2 --watch
      --source /data/acme.json --dest /data/certs'
    volumes:
      - letsencrypt:/data

volumes:
  letsencrypt:
    driver: local

networks:
  traefik:
    external: true
