services:
  minecraft:
    container_name: ${SERVICE}
    image: itzg/minecraft-server
    restart: unless-stopped
    ports:
     - 25565:25565
    volumes:
      - data:/data:rw
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.rule=Host(`${DYNMAP_DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${DYNMAP_PORT}
    environment:
      EULA: TRUE
      MEMORYSIZE: 8G
      PAPERMC_FLAGS: ""
      TZ: ${TZ}
      TYPE: PAPER
      VERSION: ${VERSION}
      PLUGINS: |
              https://cdn-raw.modrinth.com/data/fRQREgAc/versions/UXqPUg7D/Dynmap-3.7-beta-2-spigot.jar
    stdin_open: true
    tty: true
    
volumes:
  data:
    driver: local
  
networks:
  traefik:
    external: true
