services:
  boringtun:
    container_name: ${SERVICE}
    image: ghcr.io/ntkme/boringtun:edge
    restart: always
    ports:
      #- "5000:5000"
      - "51820:51820/udp"
    volumes:
      - /dev/net/tun:/dev/net/tun
      - config:/etc/wireguard
    labels:
      traefik.enable: false
    command:
      - wg0
    cap_add:
      - NET_ADMIN

  wireguard-ui:
    container_name: ${SERVICE}-ui
    image: ngoduykhanh/wireguard-ui:latest
    restart: always
    volumes:
      - db:/app/db
      - config:/etc/wireguard
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.${SERVICE}.rule: Host(`${DOMAIN}`)
      traefik.http.routers.${SERVICE}.entrypoints: https
      traefik.http.routers.${SERVICE}.tls.certresolver: letsencrypt
      traefik.http.services.${SERVICE}.loadbalancer.server.port: ${PORT}
    environment:
      - SESSION_SECRET
      - WGUI_USERNAME=${WGUI_USERNAME}
      - WGUI_PASSWORD=${WGUI_PASSWORD}
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    cap_add:
      - NET_ADMIN
    logging:
      driver: json-file
      options:
        max-size: 50m
    depends_on:
      - ${SERVICE}
    network_mode: service:${SERVICE}-ui

volumes:
  config:
    driver: local
  db:
    driver: local

networks:
  traefik:
    external: true
  wiregaurd:
    external: true